Dr/styling
CodeforHawaii/kuka pull request #10
Opened 2021-01-05 02:15 UTC by davidrideout

* add loading of fonts
* add svg loader
* load custom theme json file colors
* add user flows for password reset and other pages (logic still needs to be implement)
* implement account page and updating user profile
* add styling to various existing pages.

2021-01-12 03:32 UTC, davidrideout commented
Btw I added the swift file so my xcode would build -- not sure if will break yours. I can clean it up a little if necessary.

2021-01-19 07:09 UTC, johnkmzhou requested changes
Just a change request and a comment. Will post other thoughts in Slack channel.

2021-01-19 07:09 UTC, johnkmzhou commented on KukaApp/App.js
> +            <StatusBar />
I don't believe this is necessary.

2021-01-19 07:09 UTC, johnkmzhou commented on KukaApp/navigation/AuthNavigator.js
> +      <Screen name="My Account" component={MyAccountNavigator} />
Probably don't need navigators for some of these. That being said, we can leave it as is for now.

2021-02-09 04:43 UTC, johnkmzhou approved these changes
lgtm

2021-02-09 04:43 UTC, merged