Implement granicus api crawler
CodeforHawaii/kuka pull request #6
Opened 2020-10-02 23:03 UTC by davidrideout

* Implemented web crawler to update firestore with granicus data. Unfortunately we need higher tier access to run it as a cronjob.
* Fixed eslint settings for /functions and /web
* Did a really janky implementation for Agenda items until we can discuss further (see slack)

2020-10-04 15:15 UTC, davidrideout commented on web/src/views/home/AgendaDetailView/AgendaPanel.tsx
> +        <MuiLinkify>{agendaItem.location.trim()}</MuiLinkify>
Move `trim()` to crawler.

2020-10-08 05:52 UTC, johnkmzhou requested changes
Just a minor change request.

2020-10-08 05:52 UTC, johnkmzhou commented on functions/package.json
>    "dependencies": {
You don't need some of these dependencies.

2020-10-08 23:35 UTC, davidrideout commented on functions/package.json
>    "dependencies": {
Removed unnecessary dependencies

2020-10-08 23:35 UTC, davidrideout commented on web/src/views/home/AgendaDetailView/AgendaPanel.tsx
> +        <MuiLinkify>{agendaItem.location.trim()}</MuiLinkify>
fixed

2020-10-09 09:56 UTC, johnkmzhou approved these changes
lgtm

2020-10-09 09:56 UTC, merged